### ISSUE TITLE
Input of float values with exponent  gives wrong values

### ISSUE THREAD

**Issue by ghost** [pahihu/SPOC#1]
This report is describes the behaviour of the SPOC compiler that I compiled from this repository for a 32-bit Debian-8 (Jessie) I compiled both with and without the INMOS libraries.

The procedures so.read.echo.real32 and so.read.echo.real64 fail to properly convert float numbers with an explicit exponent. In a converted number, the exponent is multiplied by a factor of 10.
In the same way, the procedures STRINGTOREAL32 and STRINGTOREAL64 do not properly convert float numbers with an explicit exponent. The exponent of the converted number is 10 times that of the exponent given in the string representation of the number. The KRoC-Compiler (https://github.com/concurrency/kroc) does not exhibit that behaviour.

For now I have no idea how to fix that bug. However, I would love to know whether others can confirm my obervations.

Best regards
Boris Gaertner

For your convenience, you find an archive with two test programs here:
[Testprograms.tar.gz](https://github.com/pahihu/SPOC/files/4775037/Testprograms.tar.gz)

The archive file contains two folders, one for each test program. Be sure to read the README.txt
files

**Comment by pahihu** [comment]
Hi,

Thanks for reporting this bug.

The STRINGTOREAL32 and STRINGTOREAL64 procedures in convert.occ
used BYTE ‘0’ to terminate the strings before conversion instead of BYTE 0

I have fixed this and pushed to GitHub.

Thanks,
pahihu

**Comment by ghost** [comment]
Thank you a lot for the quick fix. My sample programs are now running as they should.
